project_id  = "storied-box-478112-e8"
region      = "europe-west4"
location    = "europe-west4-a"
network_name = "vpc-data-platform"
subnet_name  = "subnet-data-platform-ew4"
gke_name     = "gke-datahub-ew4"
